version: '3'
services:
  fastapi-app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: booklib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
